apiVersion: batch/v1
kind: Job
metadata:
  name: pi-8
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(8 + 1000)"]
      restartPolicy: Never
