apiVersion: batch/v1
kind: Job
metadata:
  name: pi-7
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(7 + 1000)"]
      restartPolicy: Never
